name: Datei mit Datumsinfo erstellen
on:
  push:
    branches:
      - master
jobs:
  job-apk-bauen:
    name: Debug-APK bauen
    runs-on: ubuntu-latest
    steps:
      - name: Datei erstellen
        run: |
          date '+%e.%m.%Y: %A, %j. Tag im Jahr, liegt in Kalenderwoche %V.' > datum.txt
      - name: Datei hochladen
        uses: actions/upload-artifact@v3
        with:
          name: Ergebnis
          path: datum.txt
          if-no-files-found: error
          retention-days: 2